name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
    
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: ubuntu-20.04
            os: ubuntu-20.04
            handles-release: true
            
          - name: osx_11.0-x86_64
            os: macos-11.0
            
          - name: win-x86_64
            os: windows-latest

    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget
        
    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'
        
    - name: Set the release version (if applicable)
      run: |
        echo "TAGGED_VERSION=${{ steps.version.outputs.full_without_prefix }}" >> $GITHUB_ENV
        echo Set version to ${{ steps.version.outputs.full_without_prefix }}
      shell: bash
      if: steps.version.outputs.is_valid == 'true' && github.event_name == 'release'

    - name: Check .NET versions available
      id: dotnet-versions
      run: dotnet --list-runtimes
      
    - name: Setup .NET Core 3.1.x and 6.0.x
      uses: actions/setup-dotnet@v2
      if: !contains(steps.dotnet-versions.outputs, "Microsoft.NETCore.App 6.0.") || !contains(steps.dotnet-versions.outputs, "Microsoft.NETCore.App 3.1.")
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - run: dotnet clean --configuration Release 
    - run: dotnet nuget locals all --clear
      
    - name: Restore packages
      run: dotnet restore -v quiet
      
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test -c Release --verbosity normal

    - name: Pack
      run: dotnet pack -c Release --include-source
      if: matrix.handles-release == 'true'

    - name: Publish nuget packages to Nuget.org (if a release)
      if: steps.version.outputs.is_valid == 'true' && github.event_name == 'release' && matrix.handles-release == 'true'
      run: |
        dotnet nuget push bin\Release\*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} 
